# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mydb:
        image: postgres:10.12
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn generate
    - run: yarn migrate 
    - run: yarn test
    - run: cat coverage/Icov-report/index.html
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: coverage/Icov-report/index.html
    - run: echo hi > world.txt
    - uses: actions/upload-artifact@v2
      with:
        path: world.txt
